language: ruby
branches:
  only:
    - master
services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker build --no-cache -t cloudqq/azure-cli-alpine .
  - docker tag cloudqq/azure-cli-alpine:latest cloudqq/azure-cli-alpine:v1
  - docker push cloudqq/azure-cli-alpine
